<?php

namespace App\Controller\Admin\B2;

use App\Entity\B2\Config;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ConfigCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Config::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural("Configuration Champs d'extraction")
            ->setEntityLabelInSingular('Config')
            ->setPaginatorPageSize('50')

            ->setPageTitle('index', 'Sifflote.fr - B2 - Administration des Champs d\'extraction')
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->hideOnForm(),
            TextField::new('name'),
            TextField::new('field'),
            DateTimeField::new('begin_at'),
            DateTimeField::new('valid_at'),
        ];
    }
}
