<?php

namespace App\Controller\Admin\B2;

use App\Entity\B2\Observations;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ColorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ObservationsCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Observations::class;
    }


    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('Observations')
            ->setEntityLabelInSingular('Observation')
            ->setPaginatorPageSize('50')

            ->setPageTitle('index', 'Sifflote.fr - B2 - Administration des Observations')
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->hideOnForm(),
            TextField::new('name'),
            TextField::new('color'),
            TextField::new('bgcolor'),
        ];
    }

}
