<?php

namespace App\Controller\Admin\B2;

use App\Entity\B2\Uh;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class UhCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Uh::class;
    }
    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('UH')
            ->setEntityLabelInSingular('UH')

            ->setPageTitle('index', 'Sifflote.fr - Administration des UH')
            ->setPaginatorPageSize('50')
            ->setDefaultSort(['numero' => 'ASC'])
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id'),
            IntegerField::new('numero'),
            TextField::new('designation'),
            TextField::new('antenne'),
        ];
    }

}
